### ISSUE TITLE
3.0b5 with android mode #241 building forever

### ISSUE THREAD

**Issue by DEHiCKA** [processing/processing-android#140]
3.0b5 with android mode #241 (3.0a3) + API15 installed. It opens in andoid mode, but when I try to build anything its building forewer.

Exception in thread "Thread-35" java.lang.NoSuchMethodError: processing.mode.android.AndroidBuild.getImportedLibraries()Ljava/util/ArrayList; at processing.mode.android.AndroidBuild.copyLibraries(AndroidBuild.java:978) at processing.mode.android.AndroidBuild.createProject(AndroidBuild.java:190) at processing.mode.android.AndroidBuild.build(AndroidBuild.java:94) at processing.mode.android.AndroidMode.handleRunDevice(AndroidMode.java:242) at processing.mode.android.AndroidEditor$16.run(AndroidEditor.java:530)

**Comment by emnullfuenf** [comment]
Similar situation here. I just updated to Processing 3.0b5. Had to reinstall Android mode. Doesn't find JAR libraries in code Folder and builds forever.

No library found for com.qualcomm.vuforia.Vuforia
Exception in thread "Thread-23" java.lang.NoSuchMethodError: processing.mode.android.AndroidBuild.getImportedLibraries()Ljava/util/ArrayList;
	at processing.mode.android.AndroidBuild.copyLibraries(AndroidBuild.java:978)
	at processing.mode.android.AndroidBuild.createProject(AndroidBuild.java:190)
	at processing.mode.android.AndroidBuild.build(AndroidBuild.java:94)
	at processing.mode.android.AndroidMode.handleRunDevice(AndroidMode.java:242)
	at processing.mode.android.AndroidEditor$16.run(AndroidEditor.java:530)

**Comment by emnullfuenf** [comment]
Everything works in Processing 3.0b4.

**Comment by codeanticode** [comment]
I just pushed a [new release](https://github.com/processing/processing-android/releases/tag/latest) that should be work with beta5. You can install it manually, or wait until it shows up on the Contribution Manager. Please let me know if you still experience this issue. Thanks!

**Comment by emnullfuenf** [comment]
Thanks! Builds the examples in 3.0b5.

**Comment by DEHiCKA** [comment]
Thanks!
